title: SIYUN KIM
description: Hello world!
theme: just-the-docs

url: https://siyunkim99.github.io/1.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
