title: MIMIC
description: Mimic Is Math Interchange Club
theme: just-the-docs
url: https://siyunkim99.github.io/1.github.io/

aux_links:
  Template Repository: https://siyunkim99.github.io/1.github.io/
logo: "./images/mimic.png"
